### ISSUE TITLE
Save Bumps in Account State

### ISSUE THREAD

**Issue by kespinola** [wen-community/wen-program-library#78]
### Issue

Not all accounts save their bump to the account to be used later when computing address from seeds. This causes each instruction to burn compute units finding a match.

### Resolution
Save the bump on the account and then reference when validating address from seeds.

## Example

https://github.com/wen-community/wen-new-standard/blob/b6454c09447dcabac94ee9ad59b43b1f9bb5aead/programs/wen_new_standard/src/instructions/group/create.rs#L67

**Comment by kespinola** [comment]
Issue with bumps identified on this PR.
https://github.com/wen-community/wen-new-standard/pull/77#pullrequestreview-2037866128

**Comment by sunguru98** [comment]
PR #81 and (upcoming PR edited later after #82 created) refers to this issue. @luke-truitt
